### ISSUE TITLE
extra-1.4.3 test suite failure with GHC 8.0.1-rc3

### ISSUE THREAD

**Issue by peti** [ndmitchell/extra#12] opened 2016-04-26 15:25 UTC
Citing from http://hydra.cryp.to/build/1716096/nixlog/1/raw:

~~~~~
timeout 0.1  (sleep 2 >> print 1) == return Nothing
*** Failed! Falsifiable (after 1 test): 
Test suite extra-test: FAIL
~~~~~~

**Comment by ndmitchell** [comment] 2016-04-26 15:40
Any chance that test was run without `-threaded`? Any chance its a _really_ slow machine? Is it deterministic - has it ever passed?

**Comment by peti** [comment] 2016-04-28 12:10
> Any chance that test was run without `-threaded`?

Well, it's built with that flag according to the Cabal file, so I don't think that's possible.

> Any chance its a really slow machine?

No.

> Is it deterministic - has it ever passed?

The failure occurs only sporadically. When I restarted the build, it passed.

**Comment by ndmitchell** [comment] 2016-04-28 14:25
I would have expected a 0.1 second timeout to always occur within 2 seconds, but really it's just a statistical distribution - I guess on this particular platform the long-tail sometimes passes 2 seconds. I'll raise it to 10 seconds.

**Comment by ndmitchell** [comment] 2016-04-28 15:20
That link seems to say it works now. How many times has it failed? Can I look at the failing logs? The test immediately after checks that a `timeout 0.1` completes in `< 1` second, so is twice as strict. I'd be curious to see if that test is the one that ever fails instead.

**Comment by peti** [comment] 2016-04-28 15:57
I have seen this test fail only once. (If I had noticed any errors earlier, I'd have open a ticket before.) The build log was replaced because I triggered a re-build to see whether it would fail again. Since it didn't, it's probably reasonable to assume that those failures are rare.

**Comment by ndmitchell** [comment] 2016-04-28 19:46
I'm tempted to argue "quantum effects" or some such nonsense...

Running 10,000 times I get a maximum of 0.1250141 and a minimum of 0.1000819. The 99th percentile is 0.115664472. I'm having a hard time believing it got as high as 2 seconds, without something like serious disk thrashing, power states disabling timers or something else rather funky going on.

**Comment by peti** [comment] 2016-04-28 21:35
Well, it's conceivable that the build machine was in some extraordinary state while running those tests. Sometimes builds allocate surprisingly large amounts of memory, etc., and maybe the machine *was* thrashing. Personally, I think it's just fine to leave the code as-is and assume that we'll never see that error ever again. And if we do ... then we're screwed. :-)

**Comment by ndmitchell** [comment] 2016-04-29 09:33
There are two tests - one which requires the timeout of 0.1 to fire within 2s, and one that requires it to fire within 1s. The one that does within 1s also actually gets the duration afterwards so it can see how close it was. I've adjusted the tests to run the more stringent one first and to print out the number. If it happens again we'll be able to tell how serious it was and more information about the cause.

However, I think this might have been a GHC bug - https://ghc.haskell.org/trac/ghc/ticket/11830 - which they fixed for 8.0.1-rc4. Basically they swapped the timer implementation and screwed up a few things. Makes sense it could have had an impact here.

**Closed by ndmitchell** 2016-04-29 09:33 UTC

**Comment by peti** [comment] 2016-04-29 09:37
Thank you for your efforts investigating this issue. I regularly report test suite failures to various people here on Github and elsehwhere and I dare say that not everyone approaches the subject as professionally as you do.

**Comment by ndmitchell** [comment] 2016-04-29 09:42
And thanks for your efforts to track and report the issues. It's certainly made my software better by having test data from other people, avoiding any quirks of my systems.
